### ISSUE TITLE
Additional requirements and issues with apps/workbench

### ISSUE THREAD

**Issue by joeybaer** [szTheory/real-world-phoenix#3]
This seems to be the only repo that requires `git-lfs` which we could easily add to the docs it is needed if we want to keep it.

Unfortunately, I also received the following error when attempting to init this one:

```
Smudge error: Error downloading docs/live-balance-snapshots.mov (7f2d89059a5438c5936397d8916e4c71407a853a7acad2734b9745fc3460db61): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

What are your thoughts on how to proceed?

**Comment by szTheory** [comment]
@joeybaer How's this work for instructions in the readme? https://github.com/szTheory/real-world-phoenix/pull/4/files

**Comment by joeybaer** [comment]
@szTheory looks good, what about the issue around quotas? With this one being the only one that needs `git-lfs` currently, I wonder if right now we just take this project out and maybe mention it in the readme? I, unfortunately, do not know a solution off the top to get around the mentioned error.

As it stands on a fresh setup, mine fails on this repo due to a GitHub quota issue.

**Comment by szTheory** [comment]
I don't understand the Github quota thing. That shouldn't affect you cloning it to your local computer should it? Or is it when you try to fork it on GH?

**Comment by joeybaer** [comment]
@szTheory I had never seen it before either but also have not used `git-lfs` before. Seems Github has quotas around it, you can see this error by trying from a fresh directory and doing either of the instructions in readme EX: `git submodule update --init`

**Comment by joeybaer** [comment]
I was able to have success initializing it with the following exported `export GIT_LFS_SKIP_SMUDGE=1 `

**Comment by joeybaer** [comment]
I don't see any option to set that right away in the `.gitmodules` file but maybe we can add the environment variable to the instructions as well? I don't see why they would need these doc files for the intent of this repository

**Comment by szTheory** [comment]
Hmm is this better? https://github.com/szTheory/real-world-phoenix/pull/5 you can edit the PR however you want to make the instructions clearer
